spring:
  application:
    name: msvc-provider
  config:
    import: optional:configserver:http://microservice-config:8888

keycloak:
  auth-server-url: http://keycloak:8080
  realm: microservice-provider
  client-id: provider_auth
  client-secret: aLR42FTV5jbP2grNc4QvaHk8PEnTwo8R