spring:
  application:
    name: msvc-provider
  config:
    import: optional:configserver:http://microservice-config:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/microservice-provider/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://keycloak:8080
  realm: microservice-provider
  client-id: provider_auth
  client-secret: aLR42FTV5jbP2grNc4QvaHk8PEnTwo8R