spring:
  application:
    name: msvc-client
  config:
    import: optional:configserver:http://microservice-config:8888

keycloak:
  auth-server-url: http://keycloak:8080
  realm: microservice-client
  client-id: client_auth
  client-secret: yubn0zMVRgsqZDfwPbCaTdHdF5aWulyp

---
spring:
  profiles: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb