name: Deploy to GCP (build,test,deploy)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 34.55.45.118
          username: uscateguit
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/uscateguit/projectMSVC
            docker-compose up -d --build
